flags: {}
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
packages:
- '.'
- location:
    git: https://github.com/mpickering/slack-api.git
    commit: 305b6cfa29cb2ad1ed77b7c130f99c06bd8ab6b3
  extra-dep: true
extra-deps: []
resolver: lts-6.7
ghc-options:
    akahsa: -Wall -Werror -threaded

